### ISSUE TITLE
Prevent import to deal with partial files

### ISSUE THREAD

**Issue by targos** [cheminfo/rest-on-couch#129]

**Comment by targos** [comment]
Test with a samba share and copying the file from Windows

**Comment by targos** [comment]
Best idea so far: `stat` the file once, wait X seconds, `stat` again and check if size has changed

**Comment by lpatiny** [comment]
``` fs
var size = await ctx.getFileSize();
await delay(10000);
if (size !== await ctx.getFileSize()) {
  result.skip();
}
```

**Comment by targos** [comment]
I meant in roc itself not in the import script

**Comment by stropitek** [comment]
We had a discussion and we thought it might not be flexible enough to implement it in roc itself. According to Luc it's possible that an instrument needs 20 seconds to write the file entirely. Should all scripts wait 20 seconds, delaying the availability of the data in the database?

I'd rather have that logic to be encapsulated in the import script rather than having to configure different timeout durations in the database config object.

However I understand the proposed solution is not ideal. The delay in the import scripts is blocking subsequent imports.
